### ISSUE TITLE
Category not saving - new one created instead

### ISSUE THREAD

**Issue by ferret-e** [mageplaza/magento-2-blog#103]
### Preconditions
Trying second time to install Blog - first attempt  was in July 2016 and it crashed whole system, removed. Just installed most recent version via composer.
Blog 2.5, Magento 2.2.1

### Steps to reproduce
Admin - Menu - Mageplaza - Better Blog Categories
Selecting any category, changing name, pressing Save - instead of saving changes, new one created with entered name.

P.S> Back button shows

"Magento Admin
404 Error
Page not found."

(*/sales/category/index/key/* page)

**Comment by carloricci84** [comment]
The problem is that the id field in the database is category_id. To fix the problem I added a condition to add the data category_id to the data var  in vendor/mageplaza/magento-2-blog-extension/Controller/Adminhtml/Category/Save.php around at line 165 in version 2.4.3. Now make sure you override the class instead of making the change directly in the vendors.

```
if ($data = $this->getRequest()->getPost('category')) {
            if(isset($data['id'])){
                $data['category_id']=$data['id'];
            }
```
