### ISSUE TITLE
Is your extension so bad so you need to steal Magefan Blog reviews?

### ISSUE THREAD

**Issue by magefan** [mageplaza/magento-2-blog#178]
We have noticed that you have[ issues with the customer reviews ](https://magefan.com/blog/what-you-should-know-about-reviews-at-mageplaza-website)for your blog extension. 

If you need to improve the quality of your Blog extension code, please contact us. We have certified Magento developers that can help you. We really have a great experience in creating [Blog extension for Magento 2](https://magefan.com/magento2-extensions).

**Comment by NgoDuVietHung97** [comment]
Hi @magefan,
Thank you for contacting us.
We will check this issue and will give you a satisfactory answer as soon as possible.
Thank you!

**Comment by magefan** [comment]
@NgoDuVietHung97 , we see you already have removed some reviews that you borrowed from the [Magento 2 Blog Module](https://magefan.com/magento2-blog-extension) by Magefan. Thank you.
But there is still a review that you should remove too. Please check

https://prnt.sc/n8y57q
original: https://prnt.sc/n8y5dz

Also, we have found duplicated reviews
1.
https://prnt.sc/n8y67j
https://prnt.sc/n8y6ey

2. 
https://prnt.sc/n8y70m
https://prnt.sc/n8y74v

You have a very lazy content manager and it is always better to do not write a review to yourself.

**Comment by ngantq** [comment]
Hi Magefan,

This is Summer, marketing leader from Mageplaza. We recognized this problem a while ago and was really disappointed by how everything happened. I personally confirm that some reviews on our Blog extension were completely similar to yours and vice versa, HOWEVER, these reviews were NOT copied by anyone from Mageplaza. All of these reviews, after being noticed about the duplication, were taken down because we do not need them.

First of all, I want to emphasize that we Mageplaza have no reasons to copy ANYTHING from ANYONE. Our Blog extension has been known widely and positively on the marketplace for a long time, enough to say that we don't have to use any words from any other vendors to prove our product quality. Before this happened, we had already had more than 90 positive reviews for Mageplaza Blog extension.

Second, all of our customers need to buy extensions to review our products. All of our reviews are from actual buyers. We DO NOT write reviews on our own. Reviews submitted by buyers are to be checked whether or not they are related, appropriate and spelling mistake free. Hence, we have no responsibilities for the duplication.

All these duplicated reviews were from the same person. As much as we are so disappointed about this behavior, we do not know the purpose behind all of this and we cannot share the information about our customers publicly. Should you want to work on this directly with me, please contact summer@mageplaza.com

Our reputation and prestige of our brand are massively more important than only some positive reviews on a product that we are already so confident about. We haven't officially raised our voice yet because we want to solve this professionally and appropriately. We kindly ask the same from Magefan too.  

Any further discussion should take place professionally between Mageplaza and Magefan. Please contact summer@mageplaza.com

Regards!
