### ISSUE TITLE
Inventory Management Based On customer Group

### ISSUE THREAD

**Issue by pramod-mishra** [mageplaza/magento-2-blog#236]
i am currently an issue with managing inventory in magento 2. basically my goal is to manage inventory based on customer groups.

i.e i want to set limit based on groups that a product has 60 quantity then a b2c customer can only purchase 3 items and after that he cannot order anymore and where as a b2b customer can order maximum of 20 quantity and after that quantity he cannot order any more

is there a way to achieve this. thanks in advance

**Comment by Bang512** [comment]
Hi @pramod-mishra,

Thanks for contacting us.

I'm not sure I can understand your problem. Could you please explain your problem with our Blog extension?
If possible, please send me a screenshot of your problem.

I look forward to your response.
Thank you in advance!

**Comment by pramod-mishra** [comment]
actually am not using any extension but i want a solution for a problem where a customer group cannot buy product more than allowed quantity

**Comment by Bang512** [comment]
Hi @pramod-mishra,

I really want to help you. However, as the issue is out of our control, I highly recommend you to leave your queries here:
https://magento.stackexchange.com
They will support you better

I hope you understanding. If you have any feedback or questions about the Mageplaza extensions, don't hesitate to ping me/ shoot me an email. I am willing to help you out!

**Comment by Bang512** [comment]
Closed due no response within 7 days.
