### ISSUE TITLE
Admin Topic edit flushed the topic from post

### ISSUE THREAD

**Issue by Vinit-github** [mageplaza/magento-2-blog#318]
Description (*)

When i edit the topic name from admin and save it, it remove the posts associated with it.

Expected behavior (*)
Updated topic name with associated post in post tab should display in Topic

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create New Topic and Post
2. Go to Topic
3. Assign New post to the topic from post tab
3. save the topic
3. Go to topic and Edit name 
4. click on Save or save and continue
5.  go to post tab in topic

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

[ https://www.awesomescreenshot.com/video/4527025?key=95ea190c12703966e840ea409ef37b7e  ]

[](google.com)

**Comment by giaphn** [comment]
I have checked on the local but do not figure out the issue you reported: https://www.dropbox.com/s/wkxsp2tq56jahkg/blog.webm?dl=0. It seems that the current situation occurs on your site only.
For further support, please submit a ticket at https://www.mageplaza.com/contact.html so that we can work on it.
I do value your help in this matter and look forward to hearing from you soon.

**Comment by giaphn** [comment]
Closed due no response within 7 days.
