### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by valentinmanthei** [mageplaza/magento-2-blog#85]
Thank you for your great plugin!

During usage I found some styling issues and it would great if you would fix them or at least point out how to add own LESS overrides.

magento-2-blog version: 2.4.4

1. The media queries for .post-view img.img-responsive have fixed heights and relative width (100%), which makes the aspect ratio of the post image inconsistent. The post image gets stretched or jolted if the window size changes. The height should be "auto" to make sure the aspect ratio of the image is always appropriate.

2. Changing the blog's color in the admin panel does not have any effect.

3. Columns in the post view have inconsistent paddings. Sometimes multiple containers (e.g. col-xs-12) are nested and the paddings sum up. Hence the alignment of boxes is not properly.
![image](https://user-images.githubusercontent.com/641300/29399376-436274fa-8329-11e7-95be-ae7a85f12065.png)

4. Could you please add a small step-by-step guide to adjust the blog LESS/CSS manually?

Thank you,
Valentin

**Comment by Kenny1994** [comment]
Hi,
Regarding your all questions, I can answer as below: 
1. I agreed with you should put the height as " auto ". I will add the change to develop branch soon
2. Changing the blog's color problem has been fixed, please see this commit: https://github.com/mageplaza/magento-2-blog/commit/02f616af69228a884d273b135161c55360bb38ff .For all hot fixes, I put it in the develop branch, so please download it from develop branch instead of master branch. 

3,4. 
I didn't understand your mean clearly. However, if you want to change any style of the blog. It's very easy, you just change it at _module.less.
Keep in mind, you have to deploy the page again or delete the blog module setup and re-setup it to change the effect. 
Also, you can also change directly the style in the file pub/static/frontend/YourTheme/YourThemeName/en-US/css/ style-m.css, style-l.css. Or pub/static/frontend/YourTheme/YourThemeName/en-US/Mageplaza_Blog/css/source/_module.less. 

If you have any further questions, feel free to contact me.
Thank you!
